version: '3'

services:
  rate-limiter:
    build: .
    container_name: rate-limiter
    environment:
      - REDIS_URL=redis:6379
    depends_on:
      - redis
    ports:
      - "8080:8080"
    networks:
      - rate-limiter-network

  redis:
    image: "redis:6.2.5"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - rate-limiter-network

networks:
  rate-limiter-network:
    driver: bridge
